### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by mannoola8** [pakfur/metascan#17]
1- When the program runs, it shows this error message in the terminal then opens the program: 
DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=9.75, pixelsize=15, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-15) dpi=96
2- When closing then opening the program again, the PATHS are gone, I have to re-add the PATH and Scan again.
3- Clicking on Refresh makes directories under PATHS disappear, I have to re-add the path and scan it again for the folders to appear.
4- Right-Clik an image then clicking on Open, does not open the image (double-click works)
5- Right-Clik an image then clicking on Open Folder, returns an error, but the folder actually opens.

![Image](https://github.com/user-attachments/assets/2f4df460-05df-48aa-a79c-56be355c01c5)

**Comment by pakfur** [comment]
These were a bunch of windows specific problems. I have applied what I think are the right fixes. I don’t have a windows machine right now to fully test.

 1. DirectWrite Font Error 
   
  - Fix: Added Windows-specific font handling 
  
 2. Paths Not Persisting Between Sessions 
  
   - Fix: Updated filters_panel.py to use proper config path
  
  3. Refresh Making Directories Disappear 

  - Fix: Connected the Refresh action and created refresh_view() method
  
  4. Right-Click Open Image Not Working 

  - Fix: Improved on_context_open_requested() method
  
  5. Right-Click Open Folder Error Message 

  - Fix: Removed check=True from Windows explorer subprocess call

**Comment by pakfur** [comment]
Thanks for the report. There were some windows specific issues. I checked the windows code and I am putting in some fixes

 1. DirectWrite Font Error 
  add a Windows-specific font handling in main() function, "Segoe UI”

  2. Paths Not Persisting Between Sessions 
  use proper config path for windows platforms

  3. Refresh Making Directories Disappear
   Refresh action was created but never connected to any functionality
   Added refresh functionality that reloads media and filters

  4. Right-Click Open Image Not Working 
Improved on_context_open_requested() method for windows

  5. Right-Click Open Folder Error Message 
Removed check=True from explorer subprocess call

**Comment by pakfur** [comment]
I addressed these bugs in the latest release v0.10.

**Comment by mannoola8** [comment]
Bugs fixed except for:

DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="8514oem", pointsize=9.75, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=96

This still appears in terminal when the program starts.
